###############################################################################
# Copyright (c) 2021 Xilinx, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT
###############################################################################
DRIVER_LIB_VERSION = v1.0

library := libxil.a

include ../common.mk

INCLUDEDIR += $(LOCAL_DIR)/../uartps
